/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BcAiRouteImport } from './routes/bc-ai'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClientIdRouteImport } from './routes/clientes.$clientId'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmLeadIdRouteImport } from './routes/crm.$leadId'
import { Route as CrmKanbanRouteImport } from './routes/crm.kanban'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BcAiRoute = BcAiRouteImport.update({
  id: '/bc-ai',
  path: '/bc-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesClientIdRoute = ClientesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientesRoute,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadIdRoute = CrmLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => CrmRoute,
} as any)
const CrmKanbanRoute = CrmKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => CrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bc-ai': typeof BcAiRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRouteWithChildren
  '/despesas': typeof DespesasRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/crm/$leadId': typeof CrmLeadIdRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/clientes/': typeof ClientesIndexRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bc-ai': typeof BcAiRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/crm/$leadId': typeof CrmLeadIdRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/clientes': typeof ClientesIndexRoute
  '/crm': typeof CrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bc-ai': typeof BcAiRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRouteWithChildren
  '/despesas': typeof DespesasRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/crm/$leadId': typeof CrmLeadIdRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/clientes/': typeof ClientesIndexRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bc-ai'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/despesas'
    | '/login'
    | '/relatorios'
    | '/vendas'
    | '/clientes/$clientId'
    | '/crm/$leadId'
    | '/crm/kanban'
    | '/clientes/'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bc-ai'
    | '/configuracoes'
    | '/despesas'
    | '/login'
    | '/relatorios'
    | '/vendas'
    | '/clientes/$clientId'
    | '/crm/$leadId'
    | '/crm/kanban'
    | '/clientes'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/bc-ai'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/despesas'
    | '/login'
    | '/relatorios'
    | '/vendas'
    | '/clientes/$clientId'
    | '/crm/$leadId'
    | '/crm/kanban'
    | '/clientes/'
    | '/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BcAiRoute: typeof BcAiRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CrmRoute: typeof CrmRouteWithChildren
  DespesasRoute: typeof DespesasRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bc-ai': {
      id: '/bc-ai'
      path: '/bc-ai'
      fullPath: '/bc-ai'
      preLoaderRoute: typeof BcAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$clientId': {
      id: '/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof ClientesClientIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/$leadId': {
      id: '/crm/$leadId'
      path: '/$leadId'
      fullPath: '/crm/$leadId'
      preLoaderRoute: typeof CrmLeadIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/kanban': {
      id: '/crm/kanban'
      path: '/kanban'
      fullPath: '/crm/kanban'
      preLoaderRoute: typeof CrmKanbanRouteImport
      parentRoute: typeof CrmRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesClientIdRoute: typeof ClientesClientIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClientIdRoute: ClientesClientIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface CrmRouteChildren {
  CrmLeadIdRoute: typeof CrmLeadIdRoute
  CrmKanbanRoute: typeof CrmKanbanRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmLeadIdRoute: CrmLeadIdRoute,
  CrmKanbanRoute: CrmKanbanRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BcAiRoute: BcAiRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CrmRoute: CrmRouteWithChildren,
  DespesasRoute: DespesasRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
